
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/objects.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

#define ERR_FUNC(func) ERR_PACK(ERR_LIB_OBJ,func,0)
#define ERR_REASON(reason) ERR_PACK(ERR_LIB_OBJ,0,reason)

static ERR_STRING_DATA OBJ_str_functs[]=
	{
{ERR_FUNC(OBJ_F_OBJ_ADD_OBJECT),	"OBJ_add_object"},
{ERR_FUNC(OBJ_F_OBJ_CREATE),	"OBJ_create"},
{ERR_FUNC(OBJ_F_OBJ_DUP),	"OBJ_dup"},
{ERR_FUNC(OBJ_F_OBJ_NAME_NEW_INDEX),	"OBJ_NAME_new_index"},
{ERR_FUNC(OBJ_F_OBJ_NID2LN),	"OBJ_nid2ln"},
{ERR_FUNC(OBJ_F_OBJ_NID2OBJ),	"OBJ_nid2obj"},
{ERR_FUNC(OBJ_F_OBJ_NID2SN),	"OBJ_nid2sn"},
{0,NULL}
	};

static ERR_STRING_DATA OBJ_str_reasons[]=
	{
{ERR_REASON(OBJ_R_MALLOC_FAILURE)        ,"malloc failure"},
{ERR_REASON(OBJ_R_UNKNOWN_NID)           ,"unknown nid"},
{0,NULL}
	};

#endif

void ERR_load_OBJ_strings(void)
	{
#ifndef OPENSSL_NO_ERR

	if (ERR_func_error_string(OBJ_str_functs[0].error) == NULL)
		{
		ERR_load_strings(0,OBJ_str_functs);
		ERR_load_strings(0,OBJ_str_reasons);
		}
#endif
	}