#! /bin/sh
# You may redistribute this program and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
DEFS="${1-ncurses_defs}"
cat <<EOF
/*
 * This file is generated by $0
 */

#ifndef NC_DEFINE_H
#define NC_DEFINE_H 1

EOF

${AWK-awk} <$DEFS '
!/^[@#]/ {
	if ( NF == 1 )
	{
		print "#ifndef", $1
		print "#define", $1, "0"
		print "#endif"
		print ""
	} else if ( NF != 0 ) {
		print "#ifndef", $1
		printf "#define"
		for (n = 1; n <= NF; n++) {
			printf " %s", $n
		}
		print ""
		print "#endif"
		print ""
	}
}
END	{
print "#endif /* NC_DEFINE_H */"
	}
'