
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * Silly little program to generate the help.c source file
 * from the less.hlp text file.
 * help.c just contains a char array whose contents are 
 * the contents of less.hlp.
 */

#include <stdio.h>

	int
main(argc, argv)
	int argc;
	char *argv[];
{
	int ch;
	int prevch;

	printf("/* This file was generated by mkhelp from less.hlp */\n");
	printf("#include \"less.h\"\n");
	printf("constant char helpdata[] = {\n");
	ch = 0;
	while (prevch = ch, (ch = getchar()) != EOF)
	{
		switch (ch)
		{
		case '\'':
			printf("'\\'',");
			break;
		case '\\':
			printf("'\\\\',");
			break;
		case '\b':
			printf("'\\b',");
			break;
		case '\t':
			printf("'\\t',");
			break;
		case '\n':
			if (prevch != '\r') 
				printf("'\\n',\n");
			break;
		case '\r':
			if (prevch != '\n') 
				printf("'\\n',\n");
			break;
		default:
			if (ch >= ' ' && ch < 0x7f)
				printf("'%c',", ch);
			else
				printf("0x%02x,", ch);
			break;
		}
	}
	/* Add an extra null char to avoid having a trailing comma. */
	printf(" 0 };\n");
	printf("constant int size_helpdata = sizeof(helpdata) - 1;\n");
	return (0);
}