
/*
 * You may redistribute this program and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/buffer.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

#define ERR_FUNC(func) ERR_PACK(ERR_LIB_BUF,func,0)
#define ERR_REASON(reason) ERR_PACK(ERR_LIB_BUF,0,reason)

static ERR_STRING_DATA BUF_str_functs[]=
	{
{ERR_FUNC(BUF_F_BUF_MEMDUP),	"BUF_memdup"},
{ERR_FUNC(BUF_F_BUF_MEM_GROW),	"BUF_MEM_grow"},
{ERR_FUNC(BUF_F_BUF_MEM_GROW_CLEAN),	"BUF_MEM_grow_clean"},
{ERR_FUNC(BUF_F_BUF_MEM_NEW),	"BUF_MEM_new"},
{ERR_FUNC(BUF_F_BUF_STRDUP),	"BUF_strdup"},
{ERR_FUNC(BUF_F_BUF_STRNDUP),	"BUF_strndup"},
{0,NULL}
	};

static ERR_STRING_DATA BUF_str_reasons[]=
	{
{0,NULL}
	};

#endif

void ERR_load_BUF_strings(void)
	{
#ifndef OPENSSL_NO_ERR

	if (ERR_func_error_string(BUF_str_functs[0].error) == NULL)
		{
		ERR_load_strings(0,BUF_str_functs);
		ERR_load_strings(0,BUF_str_reasons);
		}
#endif
	}