#! /bin/sh
# You may redistribute this program and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
: ${AWK-awk}
DATA=${1-../../include/Caps}

data=data$$
trap 'rm -f $data' 0 1 2 5 15
sed -e 's/[	][	]*/	/g' < $DATA >$data

cat <<EOF
# These definitions were generated by $0 $DATA
KEY_BREAK
KEY_SRESET
KEY_RESET
KEY_RESIZE
EOF

${AWK-awk} <$data '
/^#/		{next;}
/^capalias/	{next;}
/^infoalias/	{next;}

$5 != "-" {
		if (substr($5, 1, 4) == "KEY_" ) {
			printf "%s	%s\n", $5, $1
	}
}
'